Fix issues caused by github api pagination

diff --git a/set-team b/set-team
--- a/set-team
+++ b/set-team
@@ -19,35 +19,49 @@ if [[ "$GIVEN_NAME" == "eng-ret-web" ]]; then
     exit 0
 fi
 
-TEAM_FILTER="map(select(.name | contains(\"$GIVEN_NAME\"))) | map(.name, .id)"
-TEAM_ID_FILTER="map(select(.name | contains(\"$GIVEN_NAME\"))) | map(.name, .id) | .[1]"
+for i in 1 2 3 4 5 6 7 8 9; do
+    TEAM_FILTER="map(select(.name | contains(\"$GIVEN_NAME\"))) | map(.name, .id) | .[0]"
+    TEAM_ID_FILTER="map(select(.name | contains(\"$GIVEN_NAME\"))) | map(.name, .id) | .[1]"
 
-TEAM_INFO=$(http GET "https://api.github.com/orgs/Scout24/teams?access_token=$ACCESS_TOKEN" | jq "$TEAM_FILTER")
-TEAM_ID=$(http GET "https://api.github.com/orgs/Scout24/teams?access_token=$ACCESS_TOKEN" | jq "$TEAM_ID_FILTER")
+    TEAM_NAME=$(http GET "https://api.github.com/orgs/Scout24/teams?page=$i&per_page=30&access_token=$ACCESS_TOKEN" | jq "$TEAM_FILTER")
+    TEAM_ID=$(http GET "https://api.github.com/orgs/Scout24/teams?page=$i&per_page=30&access_token=$ACCESS_TOKEN" | jq "$TEAM_ID_FILTER")
 
-echo -e "Found team name and id: $TEAM_INFO\n"
-
-read -p "Is this correct team? [y/n] " -n 1 -r; echo
-
-if [[ $REPLY =~ ^[Yy]$ ]]; then
-    echo $TEAM_ID > "$MY_DIR/team-id.albert.txt"
-else
-    read -p "Please enter team github slug (check the url):"
-
-    if [[ "$REPLY" == "" ]]; then
-        echo "Empty slug is not accepted. Please use correct team name or slug."
-        exit 1
-    fi
-
-    TEAM_ID_FILTER="map(select(.slug | contains(\"$REPLY\"))) | map(.name, .id) | .[1]"
-    TEAM_ID=$(http GET "https://api.github.com/orgs/Scout24/teams?access_token=$ACCESS_TOKEN" | jq "$TEAM_ID_FILTER")
-
-    if [[ "$TEAM_ID" == "" ]] || [[ "$TEAM_ID" == null ]]; then
-        echo "Given slug wasn't found! Please use correct team name or slug."
-        exit 1
+    if [[ "$TEAM_NAME" == "" ]] || [[ "$TEAM_NAME" == null ]]; then
+        continue
     else
-        echo $TEAM_ID > "$MY_DIR/team-id.albert.txt"
+        echo -e "Found team name and id: $TEAM_NAME\n"
+        read -p "Is this correct team? [y/N] " -n 1 -r; echo
+
+        if [[ $REPLY =~ ^[Yy]$ ]]; then
+            echo $TEAM_ID > "$MY_DIR/team-id.albert.txt"
+            echo "Team added successfully"
+            exit 0
+        else
+            continue
+        fi
     fi
+done
+
+echo -e "I couldn't find the team :( \nLet's try another way\n"
+read -p "Please enter team slug (check github team url, for example: github.com/orgs/Scout24/teams/team-slug):"
+
+if [[ "$REPLY" == "" ]]; then
+    echo "Empty slug is not accepted. Please use correct team name or slug."
+    exit 1
 fi
 
-exit 0
+for i in 1 2 3 4 5; do
+    TEAM_ID_FILTER="map(select(.slug | contains(\"$REPLY\"))) | map(.name, .id) | .[1]"
+    TEAM_ID=$(http GET "https://api.github.com/orgs/Scout24/teams?page=$i&per_page=100&access_token=$ACCESS_TOKEN" | jq "$TEAM_ID_FILTER")
+
+    if [[ "$TEAM_ID" == "" ]] || [[ "$TEAM_ID" == null ]]; then
+        continue
+    else
+        echo $TEAM_ID > "$MY_DIR/team-id.albert.txt"
+        echo "Team added successfully"
+        exit 0
+    fi
+done
+
+echo "Given slug wasn't found! Please use correct team name or slug."
+exit 1
